---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
now I wonder what you're at!'You know the song, perhaps?" "I've heard something like it," said Alice.  
 "It goes on, you know," the Hatter continued,  
"in this way: -- --   
`Up above the world you fly,  
Like a teatray in the sky.  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Whose woods these are I think I know  
His house is in the village though;  
He will not see me stopping here  
To watch his woods fill up with snow.  
  
My little horse must think it queer  
To stop without a farmhouse near  
Between the woods and frozen lake  
The darkest evening of the year.  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
